configfile: 'config.yaml'

import os

rule all:
    input:
        de_xlxs = expand("{config['out_path']}{de_type}/deResults_{de_type}.xlsx",
                         de_type=config['de_types'])

rule runDE_TMM_Limma_Voom: # Runs DE using Pseudo_TMM_Limma_Voom approach
    input:
        data_path=config['data_path']
    params:
        out_path=config['out_path']
    output:
        config['out_path']+'Pseudo_TMM_Limma_Voom/deResults_TMM_Limma_Voom.xlsx'
    script:
          "scripts/Pseudo_TMM_Limma_Voom_DE.R"


